#!/bin/bash
#
#		Puppet Installer
#
#	Copyright (C) 2013 Alex M. Lowe (amlowe@ieee.org)
#	Released into the public domain on 2013-04-28
#
#	This script installs the latest version of Puppet from the repositories on a Debian-based system.
#	REQUIRES: Repository with package "puppet" in it, including correct dependencies.

# Get the directory where the p-i script is installed.
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

echo "Updating APT repositories..."
sudo apt-get update > /dev/null

echo "Installing Puppet agent..."
sudo apt-get install puppet

echo "Installing base configuration..."
sudo cp $DIR/puppet.conf.base /etc/puppet/puppet.conf	# The base configuration included here is the default one from the Ubuntu repositories, plus some modification to make it agent-specific.

# You can use ./p-i $MASTER_NAME to install puppet with a specific master without interaction here.
if [ "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ$1" != "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ" ]; then
	MASTER_NAME=$1
else
	echo -n "Please enter your Puppet master server's DNS name: "
	read MASTER_NAME
fi
echo $MASTER_NAME|sudo tee -a /etc/puppet/puppet.conf
sudo cp $DIR/puppet-defaults /etc/default/puppet

echo "Starting Puppet agent..."
sudo puppet agent --test >/dev/null
echo "Please login to your Puppetmaster server ($MASTER_NAME) and sign this server's key."
echo "The command is: puppet cert sign $(hostname -f)"

RESPONSE='n'
while [ $RESPONSE != "y" ]; do
	echo -n "Have you completed this signing task? (y/N)"
	read RESPONSE
	# This just allows us to assume no on an empty input.
	if [ "x$RESPONSE" == "x" ]; then
		RESPONSE=N
	fi
	if [ $RESPONSE != "y" ]; then
		echo "Please sign the key before proceeding."
	fi
done

echo "Starting Puppet agent..."
sudo puppet resource service puppet ensure=running